name: "\U0001F41E Bug report"
description: >
  Something is broken or doesn't works as it should be? Create a report to help
  us improve
labels: bug
body:
  - type: markdown
    attributes:
      value: "## System Information"
     
  - type: input
    attributes:
      label: OS
      description: Information about your Operating System
      placeholder: Windows 10 x64
      
  - type: input
    attributes:
      label: Godot Version
      placeholder: 3.4.stable, 4.0.dev (3041becc6)
      
  - type: dropdown
    attributes:
      multiple: false
      label: Plugin Version
      options: 
        - 1.0 (lastest)
    validations:
      required: true
  
