name: "\U0001F58B Feature / Enhancement proposal"
description: Suggest an idea for this project
labels: enhancement
body:
  - type: textarea
    attributes:
      label: Describe the project you are working on
